"""add_stt_config_and_expand_llm_voice_configs

Revision ID: 4936acd0ce6c
Revises: 30f5e0c3f776
Create Date: 2026-02-20 19:14:59.472016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4936acd0ce6c'
down_revision: Union[str, Sequence[str], None] = '30f5e0c3f776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('voice_config_json', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('stt_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'stt_config')
    op.drop_column('agents', 'voice_config_json')
    # ### end Alembic commands ###
